config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'pages#index', as: 'pages'

  get '/sponsorships' => 'sponsorships#index'
  get '/sponsorships/new' => 'sponsorships#new', as: 'new_sponsorships'

  get '/players' => 'players#index'
  get '/players/new' => 'players#new', as: 'new_players'
  get '/players/edit' => 'players#edit', as: 'edit_players'

  get '/diners' => 'diners#index'
  get '/diners/new' => 'diners#new', as: 'new_diners'

  get '/users/new' => 'users#new'
  post '/users' => 'users#create'
  get '/users/show' => 'users#show'

  resources :signups, except: [:delete]

  get '/session/new' => 'session#new', as: 'new_session'
  post '/session' => 'session#create'
  get '/logout' => 'session#logout'

end

app/models/signup.rb
class Signup < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :email, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :contact_number, format: { with: /\(?\d{3}(\)|\.|-)? ?\d{3}(\.|-)?\d{4}/i, on: :create }
  validates :contact_number, presence: true

  after_validation :normalize_phone_number, on: [:create, :update]

  has_one :sponsorship
  accepts_nested_attributes_for :sponsorship
  has_many :players
  accepts_nested_attributes_for :players
  has_many :diners
  accepts_nested_attributes_for :diners

  def total
    if self.additional_donation
      self.total = self.additional_donation + self.signup_type_donation
    else
      self.total = self.signup_type_donation
    end
  end

  def signup_type_donation
    if self.players.count > 0
      self.players.count * 150
    elsif self.diners.count > 0
      self.diners.count * 40
    else
      self.sponsorship.sponsor_total
    end
  end

  def change_paid_status
    if self.paid_status == "unpaid"
      self.paid_status = "paid"
    else
      self.paid_status = "unpaid"
    end
    self.save
  end


  private

  def normalize_phone_number
    working_number = self.contact_number.gsub(/\D/, "")
    unless working_number.length < 10
      working_number.insert(0, "(").insert(4, ") ").insert(9, "-")
      self.contact_number = working_number.slice(0..13)
    end
  end
  

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

  before_action :set_signup, only: [:update, :show, :edit]
  before_action :authenticate!, only: [:index, :destroy]

  def create
    @signup = Signup.new(signup_params)
    p "Create signup ccccccccccccccccccc"
    if @signup.save
      redirect_to signup_path(@signup)
    else
      case params[:commit]
      when "Add players"
        # figure out how to send params to the view????
        # maybe use an 'edit_players' path???
        redirect_to new_players_path(@signup), flash: { errors: @signup.errors.full_messages }
      when "Add sponsorships"
        redirect_to new_sponsorships_path(@signup), flash: { errors: @signup.errors.full_messages }
      when "Add diners"
        redirect_to new_diners_path(@signup), flash: { errors: @signup.errors.full_messages }
      end
    end
  end

  def show
    
  end

  def index
    @signups = Signup.all.sort_by{ |signup| signup.total }.reverse
  end

  def edit
    signup = Signup.find params[:id]
  end

  def update
    @signup = Signup.find params[:id] 
    if params[:changePaidStatus]
      @signup.change_paid_status
      if request.xhr?
        render json: { paidStatus: @signup.paid_status }
      else 
        redirect_to @signup
      end  
    else
      if @signup.sponsorship
        @signup.sponsorship.store_tee_box
      end
      @signup.update_attributes(signup_params)
      p "update signup uuuuuuuuuuuuuuuuuuuuuuuuuuu"
      p signup_params
      redirect_to @signup 
    end
  end

  private

    def signup_params
      params.require(:signup).permit(:first_name, :last_name, :company_name, :email, :street_address, :city, :state, :zip, :contact_number, :additional_donation, :paid_status, :id, players_attributes: [:id, :player_first_name, :player_last_name], diners_attributes: [:id, :diner_first_name, :diner_last_name], sponsorship_attributes: [:id, :buffet, :beverage_cart, :at_the_turn, :closest_to_pin, :longest_drive, :tee_box, :tee_box_1, :tee_box_2, :tee_box_3, :tee_box_4, :tee_box_5])
    end

    def set_signup
      @signup = Signup.find(params[:id])
    end

end

app/helpers/signups_helper.rb
module SignupsHelper

  def logged_in?
    session[:user_id]
  end

  def authenticate!
    redirect_to pages_path unless logged_in?
  end

end

app/views/signups/_signup.html.erb
<tr class="details-row">
  <td><%= "#{signup.first_name} #{signup.last_name}"%></td>
  <td><%= signup.email %></td>
  <td class="right-align"><%= signup.contact_number %></td>
  <td class="right-align"><%= number_to_currency(signup.total) %></td>
  <td class="center-align"><p><%= signup.paid_status %></p><br>
    <%= button_to "change", signup_path(signup), method: :patch, remote: true, class: "waves-effect waves-light btn-large paid-button" %>
  </td>
  <td class="center-align">
    <%= link_to "details", "#", class: "waves-effect waves-light btn-large details-button" %>
  </td>
</tr>
<tr class="signup-details">
    <td><p class="description">Contact Address:</p>
        <p><%= "#{signup.street_address}, #{signup.city}, #{signup.state}  #{signup.zip}" %></p>
    </td>
    <td>
    <ul>
    <% if signup.players.count > 0 %>
      <p class="description">Players' Names:</p>
      <% signup.players.each do |player| %>
        <li><%= "#{player.player_first_name} #{player.player_last_name}" %></li>
      <% end %>
    <% elsif signup.diners.count > 0 %>
      <p class="description">Diners' Names:</p>
      <% signup.diners.each do |diner| %>
        <li><%= "#{diner.diner_first_name} #{diner.diner_last_name}" %></li>
      <% end %>
    <% else %>
      <p class="description">Sponsorships:</p>
      <% signup.sponsorship.selected_sponsorships.each do |sponsorship| %>
        <li><%= sponsorship %></li>
      <% end %>
    <% end %>
    </ul>
    </td>
</tr>

app/views/signups/_signups_diners.html.erb
<tr>
  <td><%= "#{signup.first_name} #{signup.last_name}" %></td>
  <td><%= signup.email %></td>
  <td class="right-align"><%= signup.contact_number %></td>
  <td class="right-align">$<%= signup.total %></td>
  <td class="center-align"><%= signup.paid_status %><br>
    <%= link_to "change", signup_path(signup), class: "waves-effect waves-light btn-large paid-button" %>
  </td>
  <td class="center-align">
    <%= link_to "details", signups_path, class: "waves-effect waves-light btn-large paid-button" %>
  </td>
</tr>   

app/views/signups/_signups_players.html.erb
<tr>
  <td><%= "#{signup.first_name} #{signup.last_name}"%></td>
  <td><%= signup.email %></td>
  <td class="right-align"><%= signup.contact_number %></td>
  <td class="right-align">$<%= signup.total %></td>
  <td class="center-align"><%= signup.paid_status %><br>
    <%= link_to "change", signup_path(signup), remote: true, class: "waves-effect waves-light btn-large paid-button" %>
  </td>
  <td class="center-align">
    <%= link_to "details", signups_path, class: "waves-effect waves-light btn-large paid-button" %>
  </td>
</tr>

<div class="signup-details">
  <!-- details about this signup...players names, signup address -->
</div>

app/views/signups/_signups_sponsorships.html.erb
<tr>
  <td><%= "#{signup.first_name} #{signup.last_name}" %></td>
  <td><%= signup.email %></td>
  <td class="right-align"><%= signup.contact_number %></td>
  <td class="right-align">$<%= signup.total %></td>
  <td class="center-align"><%= signup.paid_status %><br>
    <%= link_to "change", signup_path(signup), class: "waves-effect waves-light btn-large paid-button" %>
  </td>
  <td class="center-align">
    <%= link_to "details", signups_path, class: "waves-effect waves-light btn-large paid-button" %>
  </td>
</tr>    

app/views/signups/edit.html.erb
<div class="container player-reg-info">
  <h1 class="center-align reg-info">Please update your information:</h1>
</div>

<div class="container signup-form">
  <%= form_for(@signup) do |f| %>
    <div class="user-action signup-info">
      <p class="description">Information about you:</p>
      <div class="field">
        <%= f.label :first_name, "Your First Name", class: "form-label" %><br>
        <%= f.text_field :first_name, class:"form-control" %>
      </div>
      <div class="field">
        <%= f.label :last_name, "Your Last Name", class: "form-label" %><br>
        <%= f.text_field :last_name, class:"form-control" %>
      </div>
      <div class="field">
        <%= f.label :company_name, "Company Name", class: "form-label" %><br>
        <%= f.text_field :company_name %>
      </div>
      <div class="field">
        <%= f.label :email, "Email", class: "form-label" %><br>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :street_address, "Your Street Address", class: "form-label" %><br>
        <%= f.text_field :street_address %>
      </div>
      <div class="field">
        <%= f.label :city, "Your City", class: "form-label" %><br>
        <%= f.text_field :city %>
      </div>
      <div class="field">
        <%= f.label :state, "Your State", class: "form-label" %><br>
        <%= f.text_field :state %>
      </div>
      <div class="field">
        <%= f.label :zip, "Your Zip", class: "form-label" %><br>
        <%= f.text_field :zip %>
      </div>
      <div class="field">
        <%= f.label :contact_number, "Contact Number", class: "form-label" %><br>
        <%= f.text_field :contact_number %>
      </div>
      <div class="field">
        <%= f.label :additional_donation, "Additional Donation Amount", class: "form-label" %><br>
        <%= f.text_field :additional_donation %>
      </div>
    </div>
  

  <div class="user-action players-info">
    <% if @signup.players.count > 0 %>
      <p class="description">Players' Information:</p>
        <% player_counter = 1 %>
        <%= f.fields_for :players do |ff| %>
          <div class="player-info-collection">
            <%= ff.label :player_first_name, "Player #{player_counter} First Name", class: "form-label" %><br>
            <%= ff.text_field :player_first_name %>
          </div>
          <div class="player-info-collection">
            <%= ff.label :player_last_name, "Player #{player_counter} Last Name", class: "form-label" %><br>
            <%= ff.text_field :player_last_name %>
          </div>
          <% player_counter += 1 %>
        <% end %>

    <% elsif @signup.diners.count > 0 %>
      <p class="description">Diners' Information:</p>
      <% diner_counter = 1 %>
      <%= f.fields_for :diners do |ff| %>
        <div class="player-info-collection">
          <%= ff.label :diner_first_name, "Diner #{diner_counter} First Name", class: "form-label" %><br>
          <%= ff.text_field :diner_first_name %>
        </div>
        <div class="player-info-collection">
          <%= ff.label :diner_last_name, "Diner #{diner_counter} Last Name", class: "form-label" %><br>
          <%= ff.text_field :diner_last_name %>
        </div>
        <% diner_counter += 1 %>
      <% end %>

    <% else %>
      <p class="description">Sponsorship Opportunities:</p>
      <%= f.fields_for :sponsorship do |ff| %>
        <div class="player-info-collection">
          <%= ff.check_box :buffet %>
          <%= ff.label :buffet, "$1,200 Buffet Sponsorship", class: "form-label" %><br>
        </div>
        <div class="player-info-collection">  
          <%= ff.check_box :beverage_cart %>
          <%= ff.label :beverage_cart, "$1,000 Beverage Cart Sponsorship", class: "form-label" %><br>
        </div>
        <div class="player-info-collection">
          <%= ff.check_box :at_the_turn %>
          <%= ff.label :at_the_turn, "$500 At the Turn Sponsorship", class: "form-label" %><br>
        </div>
        <div class="player-info-collection"> 
          <%= ff.check_box :closest_to_pin %>
          <%= ff.label :closest_to_pin, "$250 Closest to the Pin Sponsorship", class: "form-label" %><br>
        </div>
        <div class="player-info-collection">  
          <%= ff.check_box :longest_drive %>
          <%= ff.label :longest_drive, "$250 Longest Drive Sponsorship", class: "form-label" %><br>
        </div>
        <p class="form-label">Tee Box Signs:</p>
        <div class="player-info-collection">
            <%= ff.check_box :tee_box_1, class: "tee" %>
            <%= ff.label :tee_box_1, "$250 Tee box sign", id: "tee1", class: "form-label" %><br>
          </div>
          <div class="player-info-collection">
            <%= ff.check_box :tee_box_2, class: "tee" %>
            <%= ff.label :tee_box_2, "$400 Tee box sign + 1", id: "tee2", class: "form-label" %><br>
          </div>
          <div class="player-info-collection">
            <%= ff.check_box :tee_box_3, class: "tee" %>
            <%= ff.label :tee_box_3, "$550 Tee box sign + 2", id: "tee3", class: "form-label" %><br>
          </div>
          <div class="player-info-collection">
            <%= ff.check_box :tee_box_4, class: "tee" %>
            <%= ff.label :tee_box_4, "$700 Tee box sign + 3", id: "tee4", class: "form-label" %><br>
          </div>
          <div class="player-info-collection">
            <%= ff.check_box :tee_box_5, class: "tee" %>
            <%= ff.label :tee_box_5, "$850 Tee box sign + 4", id: "tee5", class: "form-label" %><br>
          </div>
        <% end %>
      <% end %>
      <div class="actions waves-effect waves-light btn-large confirm players-signup-button">
        <%= f.submit "Confirm Signup Information" %>
      </div>
    </div>

    </div>
  <% end %>

app/views/signups/index.html.erb
<div class="container signup-list user-action">
  <h2 class="signup-header">Signup List</h2>
  <table class="responsive-table highlight">
    <thead>
      <tr>
        <th data-field="contact">Contact Name</th>
        <th data-field="email">Email</th>
        <th class="right-align" data-field="phone">Phone Number</th>
        <th class="right-align" data-field="total">Total Donation</th>
        <th class="center-align" data-field="paid">Paid Status</th>
      </tr>
    </thead>

      <%= render partial: 'signup', collection: @signups %>
        
    </table>
</div>

app/views/signups/show.html.erb
<div class="signup-summary">
  <h2 class="center-align">Thank you for your registration!</h2>
  <h2 class="center-align">Please confirm the following information:</h2>
</div>

<div class="container signup-confirmation">
  <h3 class="signup-header">Your information:</h3>
  <ul>
    <li class="confirm-info"><%= "#{@signup.first_name} #{@signup.last_name}" %></li>
    <li class="confirm-info"><%= @signup.email %></li>
    <li class="confirm-info"><%= @signup.contact_number %></li>
    <li class="confirm-info"><%= "#{@signup.street_address}, #{@signup.city}, #{@signup.state}  #{@signup.zip}" %></li>
  </ul>
</div>

<div class="container signup-confirmation">
  <% if @signup.players.count > 0 %>
  <h3 class="signup-header">Players' names:</h3>
    <ul>
    <% player_count = 1 %>
    <% @signup.players.each do |player| %>
        <li class="confirm-info">Player <%= player_count %>: <%= "#{player.player_first_name} #{player.player_last_name}" %></li>
      <% player_count += 1 %>
    <% end %>
    </ul>
  <% elsif @signup.diners.count > 0 %>
  <h3 class="signup-header">Diners' names:</h3>
    <ul>
    <% diner_count = 1 %>
    <% @signup.diners.each do |diner| %>
        <li class="confirm-info">Diner <%= diner_count %>: <%= "#{diner.diner_first_name} #{diner.diner_last_name}" %></li>
      <% diner_count += 1 %>
    <% end %>
    </ul>
  <% elsif @signup.sponsorship %>
  <h3 class="signup-header">Sponsorships selected:</h3>
    <ul>
    <% @signup.sponsorship.selected_sponsorships.each do |sponsorship| %>
      <% if sponsorship.length > 0 %>
        <li class="confirm-info"><%= sponsorship %></li>
      <% end %>
    <% end %>
    </ul>
  <% end %>
</div>

<div class="container signup-confirmation">
  <h3 class="signup-header">Total donation amount:</h3>
  <ul>
  <% if @signup.players.count > 0 %>
    <li class="confirm-info">Total for players: $<%= @signup.players.count * 150 %></li>
  <% end %>
    <li class="confirm-info">Additional donation: $<%= @signup.additional_donation %></li>
    <li id="total-donation">TOTAL DONATION $<%= @signup.total %></li>
  </ul>
</div>

<div class="center-align buttons">
  <%= link_to "edit signup information", edit_signup_path(@signup), class: "waves-effect waves-light btn-large" %><br>
  <%= link_to "confirm", users_show_path, class: "waves-effect waves-light btn-large" %>
</div>