config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'pages#index', as: 'pages'

  get '/sponsorships' => 'sponsorships#index'
  get '/sponsorships/new' => 'sponsorships#new', as: 'new_sponsorships'

  get '/players' => 'players#index'
  get '/players/new' => 'players#new', as: 'new_players'
  get '/players/edit' => 'players#edit', as: 'edit_players'

  get '/diners' => 'diners#index'
  get '/diners/new' => 'diners#new', as: 'new_diners'

  get '/users/new' => 'users#new'
  post '/users' => 'users#create'
  get '/users/show' => 'users#show'

  resources :signups, except: [:delete]

  get '/session/new' => 'session#new', as: 'new_session'
  post '/session' => 'session#create'
  get '/logout' => 'session#logout'

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      login(@user)
      redirect_to signups_path
    else
      redirect_to new_session_path(@user), flash: { error: "Invalid credentials, please try again." }
    end
  end

  def new
    @user = User.new
  end

  def logout
    session.delete(:user_id)
    redirect_to pages_path
  end

  def login(user)
    session[:user_id] = user.id
  end

end

app/helpers/session_helper.rb
module SessionHelper

  

end

app/views/session/new.html.erb
<div class="container signup-form">
  <%= form_for :session, url: session_path(@user) do |f| %>
    <% if flash[:error] %>
      <div class="error-explanation">
        <p class="error"><%= flash[:error][0] %></p>
      </div>
    <% end %>

    <div class="user-action">
      <%= f.label :username, "Username", class: "form-label" %><br>
      <%= f.text_field :username %>

      <%= f.label :password, "Password", class: "form-label" %><br>
      <%= f.password_field :password %>

      <%= f.label :email, "Email", class: "form-label" %><br>
      <%= f.text_field :email %>

      <%= f.label :role, "Role", class: "form-label" %><br>
      <%= f.text_field :role %>

      <div class="actions waves-effect waves-light btn-large players-signup-button">
        <%= f.submit "Login" %>
      </div>
    </div>

  <% end %>
</div>