config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'pages#index', as: 'pages'

  get '/sponsorships' => 'sponsorships#index'
  get '/sponsorships/new' => 'sponsorships#new', as: 'new_sponsorships'

  get '/players' => 'players#index'
  get '/players/new' => 'players#new', as: 'new_players'
  get '/players/edit' => 'players#edit', as: 'edit_players'

  get '/diners' => 'diners#index'
  get '/diners/new' => 'diners#new', as: 'new_diners'

  get '/users/new' => 'users#new'
  post '/users' => 'users#create'
  get '/users/show' => 'users#show'

  resources :signups, except: [:delete]

  get '/session/new' => 'session#new', as: 'new_session'
  post '/session' => 'session#create'
  get '/logout' => 'session#logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KatzGolfTournament</title>
    <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'http://code.jquery.com/jquery-2.1.2.min.js' %>
  <%= javascript_include_tag 'http://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js' %>
</head>

<nav class="row">
  <% if !logged_in? %>
    <%= image_tag "Christopher_Katzenstein.jpg", class:"col s2 m2 l2 katz-pic" %>
  <% end %>
  <%= link_to "HOME", pages_path, class:"col s2 m2 l2 right-align nav-link" %>
  <% if logged_in? %>
    <%= link_to "ALL SIGNUPS", signups_path, class: "col s2 m2 l2 right-align nav-link" %>
    <%= link_to "ALL PLAYERS", players_path, class: "col s2 m2 l2 right-align nav-link" %>
    <%= link_to "ALL DINERS", diners_path, class: "col s2 m2 l2 right-align nav-link" %>
    <%= link_to "ALL SPONSORS", sponsorships_path, class: "col s2 m2 l2 right-align nav-link" %>
    <%= link_to "LOGOUT", logout_path, class: "col s2 m2 l2 right-align nav-link" %>
  <% else %>
    <%= link_to "SPONSOR", new_sponsorships_path, class: "col s2 m2 l2 right-align nav-link" %>
    <%= link_to "REGISTER PLAYERS", new_players_path, class: "col s2 m2 l2 right-align nav-link" %>
    <%= link_to "DINNER ONLY", new_diners_path, class: "col s2 m2 l2 right-align nav-link" %>
    <%= link_to "CONTACT INFO", users_show_path, class: "col s2 m2 l2 right-align nav-link" %>
  <% end %>
  </nav>


<body>

   <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>How many players would you like to add?</h4>
      <h5>(including yourself)</h5>
    </div>
    <div class="modal-footer">
      <%= form_tag(new_players_path, method: "get") do %>
        <%= label_tag(:number, "Total number of players:") %>
        <%= text_field_tag(:number) %>
        <%= submit_tag("register players", class: "waves-effect waves-light btn-large modal-action modal-close waves-effect waves-green btn-flat") %>
      <% end %>
    </div>
  </div>
  </div>

<%= yield %>

</body>

<footer>
  <div class="container center-align charity-info">
    <%= link_to "Proceeds benefit the Christopher Katzenstein Scholarship Fund", new_session_path, class: "col s2 m2 l2 right-align login-link" %><br>
    <%= link_to "Federal Tax ID #0400517142", users_new_path, class: "col s2 m2 l2 right-align login-link" %>
  </div>
</footer>

</html>